In [1]:
# Import NumPy as its abbreviation 'np'

import numpy as np

In [3]:
# Create a 1-dimensional NumPy array using np.array()

d1 = np.array([1, 2, 3])

# Create a 2-dimensional NumPy array using np.array()

d2 = np.array([[4, 5, 6],
              [7, 8, 9]])

# Create a 3-dimensional Numpy array using np.array()

d3 = np.array([[[10, 11, 12],
               [13, 14, 15]],
              [[16, 17, 18],
              [19, 20, 21]]])

d1, d2, d3

(array([1, 2, 3]),
 array([[4, 5, 6],
        [7, 8, 9]]),
 array([[[10, 11, 12],
         [13, 14, 15]],
 
        [[16, 17, 18],
         [19, 20, 21]]]))

In [5]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)

print(f"d1 shape : {d1.shape}")
print(f"d1 dimensions : {d1.ndim}")
print(f"d1 data type : {d1.dtype}")
print(f"d1 size : {d1.size}")
print(f"d1 type : {type(d1)}")

# Attributes of 2-dimensional array

print(f"d2 shape : {d2.shape}")
print(f"d2 dimensions : {d2.ndim}")
print(f"d2 data type : {d2.dtype}")
print(f"d2 size : {d2.size}")
print(f"d2 type : {type(d2)}")

# Attributes of 3-dimensional array

print(f"d3 shape : {d3.shape}")
print(f"d3 dimensions : {d3.ndim}")
print(f"d3 data type : {d3.dtype}")
print(f"d3 size : {d3.size}")
print(f"d3 type : {type(d3)}")

d1 shape : (3,)
d1 dimensions : 1
d1 data type : int32
d1 size : 3
d1 type : <class 'numpy.ndarray'>
d2 shape : (2, 3)
d2 dimensions : 2
d2 data type : int32
d2 size : 6
d2 type : <class 'numpy.ndarray'>
d3 shape : (2, 2, 3)
d3 dimensions : 3
d3 data type : int32
d3 size : 12
d3 type : <class 'numpy.ndarray'>


In [20]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created

import pandas as pd

Dataf1 = pd.DataFrame(d1)
Dataf2 = pd.DataFrame(d2)

Dataf1
Dataf2

# Pandas will take only 2d numpy array and create its dataframe

d4 = d3.reshape(4,3)
Dataf3 = pd.DataFrame(d4)
Dataf3

0   1   2
0  10  11  12
1  13  14  15
2  16  17  18
3  19  20  21

In [23]:
# Create an array of shape (10, 2) with only ones

d_ones = np.ones(shape=(10,2))
d_ones

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [25]:
# Create an array of shape (7, 2, 3) of only zeros

d_zeros = np.zeros(shape=(7,2,3))
d_zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [27]:
# Create an array within a range of 0 and 100 with step 3

d_arange = np.arange(0,100,3)
d_arange

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [37]:
# Create a random array with numbers between 0 and 10 of size (7, 2)

d_randint = np.random.randint(10, size=(7,2))
d_randint

array([[6, 5],
       [2, 9],
       [7, 9],
       [6, 0],
       [4, 5],
       [2, 0],
       [4, 5]])

In [39]:
# Create a random array of floats between 0 & 1 of shape (3, 5)

d_rand = np.random.random((3,5))
d_rand

array([[0.09707551, 0.75072948, 0.22198222, 0.27244817, 0.68122677],
       [0.52764375, 0.00588315, 0.30532137, 0.08984312, 0.58690115],
       [0.75239439, 0.8357871 , 0.53330845, 0.15851092, 0.79105702]])

In [42]:
# Set the random seed to 42

np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)

d_rand_seed = np.random.randint(10, size=(4,6))
d_rand_seed

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

In [45]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable

d5 = np.random.randint(1, 10, size=(3,7))
print(d5)

# Find the unique numbers in the array you just created
np.unique(d5)

[[2 5 8 9 9 1 9]
 [7 9 8 1 8 8 3]
 [1 8 3 3 1 5 7]]


array([1, 2, 3, 5, 7, 8, 9])

In [47]:
# Find the 0'th index of the latest array you created

d5[0][0]

2

In [48]:
# Get the first 2 rows of latest array you created

d5[:2,:]

array([[2, 5, 8, 9, 9, 1, 9],
       [7, 9, 8, 1, 8, 8, 3]])

In [51]:
# Get the first 2 values of the first 2 rows of the latest array

d5[:2,:2]

array([[2, 5],
       [7, 9]])

In [54]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables

d6 = np.random.randint(10, size=(3,5))
d_ones = np.ones((3,5), dtype=int)
print(d6)
print(d_ones)

[[3 3 4 6 6]
 [3 6 2 5 1]
 [9 8 4 5 3]]
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [55]:
# Add the two arrays together

d6+d_ones

array([[ 4,  4,  5,  7,  7],
       [ 4,  7,  3,  6,  2],
       [10,  9,  5,  6,  4]])

In [63]:
d7 = np.add(d6,d_ones)
d7

array([[ 4,  4,  5,  7,  7],
       [ 4,  7,  3,  6,  2],
       [10,  9,  5,  6,  4]])

In [59]:
%time d6+d_ones
%time np.add(d6,d_ones)

Wall time: 0 ns
Wall time: 0 ns


array([[ 4,  4,  5,  7,  7],
       [ 4,  7,  3,  6,  2],
       [10,  9,  5,  6,  4]])

In [60]:
# Create another array of ones of shape (5, 3)

d_new_ones = np.ones((5,3), dtype=int)
d_new_ones

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [66]:
d7

array([[ 4,  4,  5,  7,  7],
       [ 4,  7,  3,  6,  2],
       [10,  9,  5,  6,  4]])

In [70]:
# Try add the array of ones and the other most recent array together

d8 = np.add(d7, d_new_ones.T)
d8

array([[ 5,  5,  6,  8,  8],
       [ 5,  8,  4,  7,  3],
       [11, 10,  6,  7,  5]])

In [68]:
# Create another array of ones of shape (3, 5)

d_new_new_ones = np.ones((3,5), dtype=int)
d_new_new_ones

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [73]:
# Subtract the new array of ones from the other most recent array

d9 = np.subtract(d8,d_new_new_ones)
d9

array([[ 4,  4,  5,  7,  7],
       [ 4,  7,  3,  6,  2],
       [10,  9,  5,  6,  4]])

In [74]:
# Multiply the ones array with the latest array

np.multiply(d9, d_new_new_ones)

array([[ 4,  4,  5,  7,  7],
       [ 4,  7,  3,  6,  2],
       [10,  9,  5,  6,  4]])

In [82]:
# Take the latest array to the power of 2 using '**'
# Do the same thing with np.square()

# np.power(d9,2)
# np.square(d9)
d10 = d9**2
d10

array([[ 16,  16,  25,  49,  49],
       [ 16,  49,   9,  36,   4],
       [100,  81,  25,  36,  16]], dtype=int32)

In [83]:
# Find the mean of the latest array using np.mean()

np.mean(d10)

35.13333333333333

In [84]:
# Find the maximum of the latest array using np.max()

np.max(d10)

100

In [85]:
# Find the minimum of the latest array using np.min()

np.min(d10)

4

In [90]:
# Find the standard deviation of the latest array

print(f"For Population {np.std(d10)}")

# By default the standard deviation is calculated for Population.
# To calculate it for Sample the denominator should be N-1 instead of N where N is number of elements.
# Delta Degree of Freedom (ddof) is the divisor used in calculations is N - ddof.
# Where N represents the number of elements. 
# By default ddof is zero.
# So, for standard devaiation of Sample the formula is:

print(f"For Sample {np.std(d10, ddof=1)}")

For Population 26.091803736465256
For Sample 27.007582709482236


In [92]:
# Find the variance of the latest array

print(f"For Population {np.var(d10)}")

# By default the variance is calculated for Population.
# To calculate it for Sample the denominator should be N-1 instead of N where N is number of elements.
# Delta Degree of Freedom (ddof) is the divisor used in calculations is N - ddof.
# Where N represents the number of elements. 
# By default ddof is zero.
# So, for standard devaiation of Sample the formula is:

print(f"For Sample {np.var(d10, ddof=1)}")

For Population 680.7822222222222
For Sample 729.4095238095239


In [94]:
d10

array([[ 16,  16,  25,  49,  49],
       [ 16,  49,   9,  36,   4],
       [100,  81,  25,  36,  16]], dtype=int32)

In [95]:
# Reshape the latest array to (3, 5, 1)

d11 = d10.reshape((3,5,1))
d11

array([[[ 16],
        [ 16],
        [ 25],
        [ 49],
        [ 49]],

       [[ 16],
        [ 49],
        [  9],
        [ 36],
        [  4]],

       [[100],
        [ 81],
        [ 25],
        [ 36],
        [ 16]]], dtype=int32)

In [96]:
# Transpose the latest array

d11.T

array([[[ 16,  16, 100],
        [ 16,  49,  81],
        [ 25,   9,  25],
        [ 49,  36,  36],
        [ 49,   4,  16]]], dtype=int32)

In [97]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)

d12 = np.random.randint(10, size=(3,3))
d13 = np.random.randint(10, size=(3,2))

In [98]:
d12

array([[9, 6, 8],
       [6, 0, 0],
       [8, 8, 3]])

In [99]:
d13

array([[8, 2],
       [6, 5],
       [7, 8]])

In [100]:
# Perform a dot product on the two newest arrays you created

d12.dot(d13)

array([[164, 112],
       [ 48,  12],
       [133,  80]])

In [101]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)

d13 = np.random.randint(10, size=(4,3))
d14 = np.random.randint(10, size=(4,3))

In [102]:
d13

array([[4, 0, 2],
       [9, 7, 5],
       [7, 8, 3],
       [0, 0, 9]])

In [103]:
d14

array([[3, 6, 1],
       [2, 0, 4],
       [0, 7, 0],
       [0, 1, 1]])

In [105]:
# Perform a dot product on the two newest arrays you created

d13.dot(d14)

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

In [106]:
# It doesn't work. How would you fix it?

# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both

d13.dot(d14.T)

array([[14, 16,  0,  2],
       [74, 38, 49, 12],
       [72, 26, 56, 11],
       [ 9, 36,  0,  9]])

In [107]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables

d15 = np.random.randint(10, size=(2,2))
d16 = np.random.randint(10, size=(2,2))

In [108]:
d15

array([[5, 6],
       [4, 0]])

In [109]:
d16

array([[0, 2],
       [1, 4]])

In [110]:
# Compare the two arrays with '>'

d15 > d16

array([[ True,  True],
       [ True, False]])

In [111]:
# Compare the two arrays with '>='

d15 >= d16

array([[ True,  True],
       [ True, False]])

In [121]:
# Find which elements of the first array are greater than 7

print(d15[d15 > 3])

# To print the indices of the ones which are greater than 3

print(np.nonzero(d15>3))

# The answers are (0,0) (0,1) and (1,0) and those will be printed in two arrays with row and column values

[5 6 4]
(array([0, 0, 1], dtype=int64), array([0, 1, 0], dtype=int64))


In [120]:
# Which parts of each array are equal? (try using '==')

d15 == d16

array([[False, False],
       [False, False]])

In [123]:
d15

array([[5, 6],
       [4, 0]])

In [171]:
d17 = np.array([[8,7],
               [3,2]])
d17

array([[8, 7],
       [3, 2]])

In [130]:
# Sort one of the arrays you just created in ascending order

np.sort(d17)

array([[7, 8],
       [2, 3]])

In [172]:
# Sort the indexes of one of the arrays you just created

np.argsort(d17)

array([[1, 0],
       [1, 0]], dtype=int64)

In [153]:
d17 = np.array([[5, 7],
                [3, 2]])

In [154]:
# Find the index with the maximum value in one of the arrays you've created

np.amax(d17)

#np.max(d17)

np.argmax(d17)

1

In [155]:
# Find the index with the minimum value in one of the arrays you've created

np.argmin(d17)

3

In [156]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created

np.argmax(d17, axis=1)

array([1, 0], dtype=int64)

In [157]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created

np.argmin(d17, axis=0)

array([1, 1], dtype=int64)

In [170]:
# Create an array of normally distributed random numbers

np.random.randn(2,2)

array([[ 0.51242373,  0.54348869],
       [ 0.02809946, -1.19708706]])

In [168]:
# Create an array with 10 evenly spaced numbers between 1 and 100

np.linspace(1,100,10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])